apiVersion: apps/v1 
kind: Deployment
metadata:
  name: fastapi-server
  labels: 
    app: fastapi 
spec:
  selector:
    matchLabels:
      app: fastapi 
  template: 
    metadata:
      labels: 
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: toandaominh1997/grow-fastapi:latest
        ports:
        - containerPort: 1234

            