# Generated by Django 4.0.6 on 2022-07-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_rename_user_name_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
