version: "3.9"
services:
  fastapi:
    build: "./src/backend/fastapi"
    ports:
      - "1234:1234"
    volumes:
      - ./src/backend/fastapi:/code
  postgres:
    build: "./src/services/postgres"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
  mongo:
    build: src/services/mongo
    ports:
      - "27017:27017"
  #kafka:
  #  build: ./src/services/kafka
  #  ports:
  #    - "9092:9092"
  #elasticsearch:
  #  build: ./src/services/elasticsearch
  prometheus:
    build: ./src/services/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    build: ./src/services/grafana
    ports:
      - "3000:3000"
  nginx:
    build: ./src/services/nginx
    ports:
      - "11111:11111"
    depends_on:
      - fastapi
      - postgres
      - redis
  traefik:
    build: ./src/services/traefik
    ports:
      - "80:80"
      - "22222:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #jenkins:
  #  build: ./src/services/jenkins
  #  ports:
  #    - "33333:8080"
  #    - "50000:50000"
