version: "3.9"

services:
  django:
    image: toandaominh1997/grows_django:latest
    ports:
      - 1000:1000
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  prometheus:
    image: toandaominh1997/grows_prometheus:latest
    ports:
      - 9090:9090
  grafana:
    image: toandaominh1997/grows_grafana:latest
    ports:
      - 3000:3000

