version: "3.9"

services:
  #elasticsearch:
  #  image: toandaominh1997/grows_elasticsearch:latest
  #  environment:
  #    - discovery.type=single-node
  #  ports:
  #    - 9200:9200
  #kibana:
  #  image: toandaominh1997/grows_kibana:latest
  #  ports:
  #    - 5601:5601
  #postgres:
  #  image: toandaominh1997/grows_postgres:latest
  #  ports:
  #    - 5432:5432
  #  environment:
  #    - POSTGRES_DB=postgres
  #    - POSTGRES_USER=user
  #    - POSTGRES_PASSWORD=grows1234
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data
  #redis:
  #  image: toandaominh1997/grows_redis:latest
  #  ports:
  #    - 6379:6379
  #  volumes:
  #    - redisdata:/data
  #nginx:
  #  image: toandaominh1997/grows_nginx:latest
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - django
  #mongo:
  #  image: toandaominh1997/grows_mongo:latest
  #  ports:
  #    - 27017:27017
  #  volumes:
  #    - ./data/mongo:/data/db/
  #django:
  #  image: toandaominh1997/grows_django:latest
  #  ports:
  #    - 1000:1000
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  #prometheus:
  #  image: toandaominh1997/grows_prometheus:latest
  #  ports:
  #    - 9090:9090
  #grafana:
  #  image: toandaominh1997/grows_grafana:latest
  #  ports:
  #    - 3000:3000
  ##airflow:
  ##  image: toandaominh1997/grows_airflow:latest
  ##  ports:
  ##    - 8080:8080
  #spark:
  #  image: toandaominh1997/grows_spark:latest
  #  environment:
  #    - SPARK_MODE=master
  #    - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #    - SPARK_RPC_ENCRYPTION_ENABLED=no
  #    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #    - SPARK_SSL_ENABLED=no
  #  ports:
  #    - '8080:8090'
volumes:
  pgdata:
  redisdata:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
