version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
  kong:
    image: docker.io/bitnami/kong:2
    ports:
      - 8050:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
volumes:
  postgresql_data:
    driver: local
