# Generated by Django 4.0.6 on 2022-07-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tinyurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128)),
                ('long_url', models.CharField(max_length=256)),
                ('domain', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tiny_url',
            },
        ),
    ]
