apiVersion: v1 
kind: Service 
metadata:
  name: redis
  namespace: ingress-nginx  
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: 1234
  selector: 
    app: redis 