# Generated by Django 4.0.6 on 2022-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('image_url', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
