# Generated by Django 4.0.6 on 2022-07-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tinyurl'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tinyurl',
            table='tinyurl',
        ),
    ]
