# Generated by Django 4.0.6 on 2022-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_tinyurl_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('overview', models.CharField(max_length=1000)),
                ('genres', models.CharField(max_length=256)),
                ('poster', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
