# Generated by Django 4.0.6 on 2022-07-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
