apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonne
  labels:
    app: fastapi
  namespace: toandaominh1997
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: spec-containers-fastapi
          image: "docker.io/redis:6.0.5"
          imagePullPolicy: Always
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: kge-gateway
  namespace: toandaominh1997
spec:
  selector:
    app: fastapi
    role: leader
    tier: backend
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer
