# Generated by Django 4.0.6 on 2022-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('origin_url', models.CharField(max_length=256)),
                ('s3_url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Video',
            },
        ),
    ]
