# Generated by Django 4.0.6 on 2022-07-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='s3_url',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
