# Generated by Django 4.0.6 on 2022-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_remove_video_s3_url_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='s3_url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
