apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: ingress-nginx
  labels: 
    app: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80