apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: ingress-nginx
  labels: 
    app: web 
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80