wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650067457
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 19
      4: 3.9.7
      5: 0.12.14
      8:
      - 5
learning_rate:
  desc: null
  value: 0.01
