name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
        os: [macos-latest, ubuntu-latest, ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -U rich
          pip install -U psutil
      - name: system info
        run: |
          python tests/sysinfo.py
