apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grow-ingress 
  annotations: {}
spec:
  ingressClassName: nginx-example 
  rules:
    - host: tonne.local 
      http:
        paths:
          - path: /foo 
            pathType: Prefix
            backend:
              serviceName: nginx
              servicePort: 80
              service:
                name: nginx
                port:
                  number: 80
          - path: /bar
            pathType: Prefix
            backend:
              service:
                serviceName: fastapi 
                servicePort: 1234
                name: fastapi 
                port:
                  number: 1234