apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
spec:
  ingressClassName: kong
  rules:
    - host: toandaominh1997.xyz
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: fastapi-server-service
                port:
                  number: 80
          - path: "/httpd"
            pathType: Prefix
            backend:
              service:
                name: web-server-service
                port:
                  number: 80
